#!/usr/bin/bash
#SBATCH --job-name=test_chain
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=50G
#SBATCH --time=150:00:00


source ~/anaconda3/bin/activate ~/anaconda3/envs/blockchain_env/
module load multichain
module load bcftools
conda activate blockchain_env

CN=test_chain
DR=/gpfs/commons/groups/gursoy_lab/aelhussein/blockchain/multichain
PT=/gpfs/commons/groups/gursoy_lab/aelhussein/blockchain/code/16k_scalability
AT=/gpfs/commons/groups/gursoy_lab/aelhussein/blockchain/data/preprocessing

#SAMPLE NUMBERS
PPL=12000
PPL_GS=2000
PPL_ES=2000
PPL_AF=4000
PPL_BC=4000


#BUILD CHAIN
python buildChain.py -cn=$CN --datadir=$DR

#RESTART CHAIN  --> This is used once chain exists. Then do not using buildChain.py
#multichaind $CN --datadir=$DR -daemon

#CLINICAL

python createStream-OMOP-Domain.py -cn=$CN --datadir=$DR -hp=$PT/data/mapping_vocab/CONCEPT_ANCESTOR.csv -dp=$PT/data/clinical/

python insertData-OMOP-Domain.py -cn=$CN --datadir=$DR -hp=$PT/data/mapping_vocab/CONCEPT_ANCESTOR.csv -dp=$PT/data/clinical/ -np=$PPL

python createStream-OMOP-Person.py -cn=$CN --datadir=$DR

python insertData-OMOP-Person.py -cn=$CN --datadir=$DR -dp=$PT/data/clinical/ --personPath=$PT/data/clinical/person.csv -np=$PPL

#GENETIC
python createStream-variants.py -cn=$CN --datadir=$DR

##WGS
python insertData-variant.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/wgs -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_GS 

python insertData-variantPerson.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/wgs -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_GS

##WES
python insertData-variant.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/wes -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_ES

python insertData-variantPerson.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/wes -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_ES

##AFFYMETRIX
python insertData-variant.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/affymetrix -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_AF

python insertData-variantPerson.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/affymetrix -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_AF

##BEADCHIP
python insertData-variant.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/beadchip -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_BC

python insertData-variantPerson.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/beadchip -mf=$PT/data/mapping_vocab/metadata.csv -np=$PPL_BC

##Analysis
python insertData-analysis.py -cn=$CN --datadir=$DR -dp=$PT/data/vcf/wgs -mf=$PT/data/mapping_vocab/metadata.csv -pc=$AT/ -rf=$AT/relatedness -np=$PPL_GS 

##GTF
python createStream-gtf.py -cn=$CN -dr=$DR

python insertData-gtf.py -cn=$CN -dr=$DR -gp=$PT/data/gtf -vp=$PT/data/vcf/wgs -ap=$PT/data/annotations



