#! /bin/bash
#SBATCH --job-name=multichain-insert
#SBATCH --partition=pe2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=aelhussein@nygenome.org
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=30G
#SBATCH --time=24:00:00

module load jupyter3
module load multichain
module load bcftools
#multichaind combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain &

ulimit -s 40000

python buildChain.py -cn=combchain -dr=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain

python createStream-OMOP-Domain.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -hp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/mapping_vocab/CONCEPT_ANCESTOR.csv -dp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/clinical/

python insertData-OMOP-Domain.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -hp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/mapping_vocab/CONCEPT_ANCESTOR.csv -dp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/clinical/

python createStream-OMOP-Person.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain

python insertData-OMOP-Person.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -dp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/clinical/ --personPath=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/clinical/person.csv

python createStream-variants.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain

python insertData-variant.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -mf=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/mapping_vocab/person_sample_mapping -dp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/vcf

python insertData-variantPerson.py -cn=combchain --datadir=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -mf=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/mapping_vocab/person_sample_mapping -dp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/vcf

#python createStream-gtf.py -cn=combchain -dr=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain

#python insertData-gtf.py -cn=combchain -dr=/gpfs/commons/groups/gursoy_lab/aelhussein/multichain -gp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/gtf -vp=/gpfs/commons/groups/gursoy_lab/aelhussein/Code/public_access_code/data/vcf 